<?php

/**
 * Implements hook_permisison().
 */
function field_index_permission() {
  return array(
      'manage field indexes' => array(
          'title' => 'Manage field indexes',
      ),
  );
}

/**
 * Implements hook_entity_info()
 */
function field_index_entity_info() {
  $info = array();

  $info['field_index'] = array('label'            => t('!quiz type', array('!quiz' => QUIZ_NAME)),
      'plural label'     => t('Field index'),
      'description'      => t('Field index'),
      'entity class'     => 'FieldIndex',
      'controller class' => 'EntityAPIControllerExportable',
      'base table'       => 'field_index',
      'fieldable'        => FALSE,
      'exportable'       => TRUE,
      'entity keys'      => array('id' => 'id', 'name' => 'name', 'label' => 'label'),
      'access callback'  => 'field_index_access_callback',
      'module'           => 'quizz',
      'admin ui'         => array(
          'path' => 'admin/structure/field-indexes',
          'file' => 'field_index.pages.inc',
      ),
  );

  return $info;
}

/**
 * Load field index entity by name.
 * @param string $name
 * @return FieldIndex
 */
function field_index_load($name) {
  $indexes = entity_load_multiple_by_name('field_index', array($name));
  return isset($indexes[$name]) ? $indexes[$name] : null;
}

/**
 * Access callback for field_index entity.
 * @param string $op
 * @param FieldIndex $field_index
 * @param stdClass $account
 */
function field_index_access_callback($op, $field_index = NULL, $account = NULL) {
  return user_access('manage field indexes', $account);
}
